---
Parameters:
  EnvironmentName:
    Description: Ec2 instance type
    Type: String
    AllowedValues: [development, production]
    ConstraintDescription: must be development or production


Mapping:
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-6869aa95
    us-west-2:
      HVM64: ami-7172b611
  EnvironmentToInstanceType:
    development:
      instanceType:t2.micro
    # we want a bigger instance for production
    production:
      instanceType: t2.small


Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref 'EnvironmentName', instanceType]
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', HVM64]


